apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: external-dns
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: external-dns
    spec:
      containers:
      - name: external-dns
        image: registry.opensource.zalan.do/teapot/external-dns:v0.4.8
        args:
        - --source=service # ingress is also possible
        - --source=ingress # ingress is also possible
        - --provider=cloudflare
        - --cloudflare-proxied # (optional) enable the proxy feature of Cloudflare (DDOS protection, CDN...)
        - --log-level=debug
        env:
        - name: CF_API_KEY
          value: "ENTER_CF_API_KEY"
        - name: CF_API_EMAIL
          value: "ENTER_CF_EMAIL"
      serviceAccountName: external-dns
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: external-dns
  name: external-dns
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole # you might need this https://coreos.com/operators/prometheus/docs/latest/troubleshooting.html
metadata:
  labels:
    app: external-dns
  name: external-dns
rules:
  - apiGroups:
      - ""
      - extensions
    resources:
      - ingresses
      - services
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app: external-dns
  name: external-dns
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: external-dns
subjects:
  - kind: ServiceAccount
    name: external-dns
    namespace: default          
